blog/urls.py
from django.urls import path
from . import views



urlpatterns = [

   
    path('',views.blog, name="blog"),
    
    path('categoria/<int:categoria_id>/', views.categoria, name="categoria"),
    
    
    
]

carro/urls.py
from django.contrib import admin
from django.urls import path
from .import views

app_name="carro"

urlpatterns = [

    
    path("agregar/<int:producto_id>/",views.agregar_producto, name="agregar"), 
    path("eliminar/<int:producto_id>/",views.eliminar_producto, name="eliminar"),
    path("restar/<int:producto_id>/",views.restar_producto, name="restar"),
    path("limpiar/",views.limpiar_carro, name="limpiar"),

    ]

proyectoFinal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('servicios/', include('servicios.urls')),
    path('blog/', include('blog.urls')),
    path('autenticacion/', include('autenticacion.urls')),
    path('contacto/', include('contacto.urls')),
    path('tienda/', include('tienda.urls')),

    path('carro', include('carro.urls')),
    
    path('', include('proyectoWebApp.urls')),
    
]

tienda/urls.py
from django.contrib import admin
from django.urls import path

from .import views


urlpatterns = [

    
    path('',views.tienda, name="tienda"),
    
    
]

tienda/models.py
from django.db import models

# Create your models here.

class categoriaProd(models.Model):
    nombre=models.CharField(max_length=70)
    created=models.DateField(auto_now=True)
    updated=models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name="categoriaProd"
        

    def __str__(self):
        return self.nombre
    

class producto(models.Model):
    nombre=models.CharField(max_length=70)
    categorias=models.ForeignKey(categoriaProd, on_delete=models.CASCADE)
    imagen=models.ImageField(upload_to="tienda", null=True, blank=True)
    precio=models.FloatField()
    disponibilidad=models.BooleanField(default=True)
    created=models.DateField(auto_now=True)
    updated=models.DateTimeField(auto_now=True)

    class Meta:

        verbose_name="producto"

    def __str__(self):
        return self.nombre
        

carro/views.py
from django.shortcuts import render

from .carro import Carro

from tienda.models import producto

from django.shortcuts import redirect

# Create your views here.

def agregar_producto(request, producto_id):
    
    carro=Carro(request)

    Producto=producto.objects.get(id=producto_id)

    carro.agregar(Producto)

    return redirect("tienda")


def eliminar_producto(request, producto_id):

    carro=Carro(request)

    Producto=producto.objects.get(id=producto_id)

    carro.eliminar(producto=producto)
    
    return redirect("tienda")


def restar_producto(request, producto_id):

    carro=Carro(request)

    Producto=producto.objects.get(id=producto_id)

    carro.restar_producto(Producto)

    return redirect("tienda")


def limpiar_carro(request, producto_id):

    carro=Carro(request)

    carro.limpiar_carro()
    
    return redirect("tienda")

tienda/views.py
from django.shortcuts import render
from .models import producto

# Create your views here.



def tienda (request):
    productos= producto.objects.all()
    return render(request, "tienda/tienda.html",{"productos":productos})

tienda/templates/carro/widget.html
    <table style="border-color: red; text-align: center;">
       
        <thead>
            
                <div style="margin-left: 20px;">
                <th style=" color: yellow; padding-top: 20px; font-size: 30px;">
                    CARRITO DE COMPRAS
                </th>
                </div>


            

            <tr style="color: white;">
                <th>Producto</th>
                <th>cantidad</th>
                <th>Suma</th>

    
            </tr>


        </thead>  
    
        <tbody>

            {% if request.session.carro.items %}
    
                {%  for key, value in request.session.carro.items %}
                    <tr>

                        <td style="color: white; font-size: 35px;" >{{value.nombre}}</td>
                        <td style="color: white;" >{{value.cantidad}}</td>
                        <td>

                            
                           <button style="background-color: rgb(50, 188, 15);"> <a href="{%url 'carro:agregar' value.producto_id %} " style="font-size: 20px; color: black; font-weight: bold;">+</a></button>
                           <button style="background-color: red;" > <a href="{%url 'carro:restar' value.producto_id %}" style="font-size: 20px; color: black; font-weight: bold;">-</a></button> <br>
                            {{value.precio}} USD

                        </td>

                    </tr>

                {% endfor %}
        
            {% else %}

                <tr>
                    <td>
                        <div style="color: rgb(14, 13, 13); background-color: white; font-size: 20px; font-weight: bold;">SIN PRODUCTOS</div>
                    </td>

                </tr>
            {% endif %}
        </tbody>

        <tfoot>

            <tr>
                <td style="color: red; font-size: 30px; font-weight: bold;">

                    TOTAL:{{importe_total_carro}}USD
                </td>

            </tr>
            
         </tfoot>


    </table>